eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/local-dev